function problems = problemCatalog()
%PROBLEMCATALOG Return the original project examples in one consistent format.
%   The duplicated constraint names in linpsol4, linpsol6, and linpsol7
%   have been corrected so that all of their original equations are kept.

problems(1) = makeProblem( ...
    'gwa14_2', 'Production maximization', ...
    [50; 40], ...
    [2, 4; 3, 1], ...
    [80; 60], ...
    ["<="; "<="], 'max');

problems(2) = makeProblem( ...
    'gwa14_4', 'Equality-constrained maximization', ...
    [1; 1; 1], ...
    [2, 1, 4; 1, 2, 1], ...
    [20; 30], ...
    ["="; "="], 'max');

problems(3) = makeProblem( ...
    'gwa14_7', 'Minimization with free variables', ...
    [10; 26; 1], ...
    [1, 1, 0; 1, 6, 0; 1, 2, 1], ...
    [4; 16; 15], ...
    [">="; ">="; ">="], 'min', true(3, 1));

problems(4) = makeProblem( ...
    'gwa14_8', 'Mixed-sign objective maximization', ...
    [3; -3], ...
    [1, 2; 3, -1], ...
    [8; 3], ...
    ["<="; "<="], 'max');

problems(5) = makeProblem( ...
    'linp', 'Three-constraint maximization', ...
    [5; 3], ...
    [1, -1; 2, 1; -3, 2], ...
    [2; 4; 6], ...
    ["<="; "<="; "<="], 'max');

problems(6) = makeProblem( ...
    'linpsol1', 'Four-variable maximization', ...
    [1; 2; 1; 1], ...
    [2, 1, 3, 1; 2, 3, 0, 4; 3, 1, 2, 0], ...
    [8; 12; 18], ...
    ["<="; "<="; "<="], 'max');

problems(7) = makeProblem( ...
    'linpsol2', 'Two-variable maximization', ...
    [-3; 6], ...
    [5, 7; -1, 2], ...
    [35; 2], ...
    ["<="; "<="], 'max');

problems(8) = makeProblem( ...
    'linpsol3', 'Unbounded minimization example', ...
    [3; -2; 0], ...
    [1, 3, 2; 2, 1, 1], ...
    [7; 4], ...
    [">="; ">="], 'min');

problems(9) = makeProblem( ...
    'linpsol4', 'Corrected three-equation maximization', ...
    [1; 2; 1], ...
    [3, 1, -1; 8, 4, -1; 2, 2, 1], ...
    [15; 50; 20], ...
    ["="; "="; "="], 'max');

problems(10) = makeProblem( ...
    'linpsol5', 'Second unbounded minimization example', ...
    [3; -4; 0], ...
    [2, 1, 3; 1, -1, 1], ...
    [5; 1], ...
    [">="; ">="], 'min');

problems(11) = makeProblem( ...
    'linpsol6', 'Corrected equality maximization', ...
    [1; 2; 3; -1], ...
    [1, 2, 1, 1; 2, 1, 5, 0; 1, 2, 3, 0], ...
    [10; 20; 15], ...
    ["="; "="; "="], 'max');

problems(12) = makeProblem( ...
    'linpsol7', 'Corrected basis-recovery example', ...
    [1; 3; 2; 0], ...
    [1, -1, -1, 2; 0, 1, 1, -1; 0, 0, 1, -1], ...
    [2; 3; 1], ...
    ["="; "="; "="], 'max');

problems(13) = makeProblem( ...
    'linpsol8', 'Mixed inequality maximization', ...
    [3; 1], ...
    [1, 1; 2, 1], ...
    [3; 4], ...
    [">="; "<="], 'max');
end


function problem = makeProblem(source, name, c, A, b, sense, objectiveSense, freeVariables)
if nargin < 8
    freeVariables = false(numel(c), 1);
end

problem = struct( ...
    'source', source, ...
    'name', name, ...
    'c', c(:), ...
    'A', A, ...
    'b', b(:), ...
    'constraintSense', string(sense(:)), ...
    'objectiveSense', objectiveSense, ...
    'freeVariables', logical(freeVariables(:)));
end
